FROM golang:1.24.1-alpine AS build
RUN apk add --no-cache git && \
    go install github.com/air-verse/air@latest

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
EXPOSE 8080
CMD ["air"]
